* Guideline

  Homework for week 03. Due: 11:59 pm on Wednesday, March 16, 2022.

 Please submit your solution files in PDF on Blackboard. Be sure to include a comment at the top of each file submitted that gives your name and email address. Multiple submissions are possible before the due date; the last submission will be graded. 



* Exercise 1 (points = 24) 

  Rewrite the statements below using quantifiers and variables. For example, a statement like "Even numbers are divisible by 2" becomes: "for each even number n, n is divisible by 2", or "for each number n, if n is an even number, then n is divisible by 2". You do not necessarily need to use the exact words or patterns as above. 

a. No two leaves are alike
b. Even integers equals twice some integer.
c. The sum of two positive integers is a positive number.



* Exercise 2 (points = 56)

  Write a negation for each statement. For example, the negation of "for any real number x, if x * x > 4 then x > 2" becomes "there exists a real number x, x * x > 4 and x <= 2".   


a.  for any real numbers x,y,z, (x + y) + z  equals to x + (y + z). 
b.  for any integer d, if 11 / d is an integer then d = 11.
c.  for any real nunber x, if x * (x + 5) > 0 then x > 0 or x < −5.
d.  for any positive integer n, if n is prime then n is odd or n = 2.
e.  for any integers a, b and c, if a − b is even and b − c is even, then a − c is even.
f.  for any integer n, if n is divisible by 6, then n is divisible by both 2 and 3.
f.  If the square of an integer is odd, then the integer is odd.


* Exercise 3 (points = 20)

Use inference rules to show the following argument is valid

Premises
- p ∨ q
- q -> r
- p ∧ s -> t
- ∼r
- ∼q → u ∧ s

Conclusion
- t


